# Generated by Django 3.1.5 on 2021-01-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_hora_extra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroohoraextra',
            name='horas',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=50),
            preserve_default=False,
        ),
    ]
