# Generated by Django 3.1.5 on 2021-01-28 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_auto_20210126_2004'),
        ('registro_hora_extra', '0002_registroohoraextra_horas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegistrooHoraExtra',
            new_name='RegistroHoraExtra',
        ),
    ]
